version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db_store
    environment:
      - POSTGRES_DB=my_db_store
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
